## Test 3.0


In [1]:
number=int(input("Enter a number: "))
if number % 2 == 0:
    print(f"{number} is even")
else:
    print(f"{number} is odd")
    

Enter a number: 4
4 is even


In [4]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [5]:
while True:
    number=int(input("Enter a number: "))
    if number == 0:
        print("You Entered: ", number)
print("Loop finished")

Enter a number: 160
Enter a number: 0
You Entered:  0
Enter a number: 


ValueError: invalid literal for int() with base 10: ''

In [9]:
def add_num(a,b) :
    
return a+b

IndentationError: expected an indented block after function definition on line 1 (3452917953.py, line 3)

In [7]:
What will be the output of this code: print(list(map(lambda x: x*x, [1, 2, 3])))?

SyntaxError: invalid syntax (2733306066.py, line 1)

In [ ]:
square of 1,2,3 : [1,4,9]

In [10]:
def filter_num(nums):
    def is_odd(num):
        return num % != 0
        odd_nums + list(filter(is_odd, nums))
    return odd_nums
nums =[1,2,3,4,5,6,7,8]
result = filter_even_nums (nums)
print("Even numbers are : ",result)

SyntaxError: invalid syntax (955370495.py, line 3)

Explain the purpose of the else block in a try-except-else construct.

exception is unasspected event during execution of program which can be handled . it is also  code run time error

In [11]:
8

8

In [30]:
class Dog:
    def __init__ (self,name,breed):
        self.name=name
        self.breed=breed
    def bark(self):
        return
    
    

In [41]:
class Dog:
    def __init__ (self, name, breed):
        self.name = name
        self.breed = breed
        
    def bark(self):
        print(f"{self.name} say hii")
        
    def bark1(self):
        print(f"{self.name} likes {self.breed}")
    
    
m = Dog("Disha","Mango")

m.bark
m.bark1()


Disha likes Mango


class variables : it is creating into their repesctive class
                  it is used in any classes with the help of parent,child 

instance variables : it is creating into anywhere in coding
                     it is used in only particualr method

map is itrate one by one element when filter is giving output basis on condition

### Numpy

In [12]:
import numpy as np


In [13]:
matrix = np.random.randint(0, 10, (3,3))
print(matrix)

[[6 3 9]
 [5 5 8]
 [2 7 8]]


In [17]:
matrix2=matrix[0:2]
print(matrix2)

[[6 3 9]
 [5 5 8]]


Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.

In [19]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[1,2,4],[3,5,7],[6,8,9]])

concatenate_axis0 = np.concatenate((m1,m2),axis=0)
print("concatenate_axis0 is: ",concatenate_axis0)
concatenate_axis1 = np.concatenate((m1,m2),axis=1)
print("concatenate_axis1 is: ",concatenate_axis1)

concatenate_axis0 is:  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 4]
 [3 5 7]
 [6 8 9]]
concatenate_axis1 is:  [[1 2 3 1 2 4]
 [4 5 6 3 5 7]
 [7 8 9 6 8 9]]


In [20]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [25]:
matrix=np.array([1,2,3,4,5,6,7,8,9,10])
clip_matrix1=np.clip(matrix,a_min=2,a_max=0)
print("clip_matrix for min2= ",clip_matrix1)

clip_matrix2=np.clip(matrix,a_min=0,a_max=8)
print("clip_matrix for max8= ",clip_matrix2)

clip_matrix3=np.clip(matrix,a_min=2,a_max=8)
print("clip_matrix is = ",clip_matrix3)

clip_matrix for min2=  [0 0 0 0 0 0 0 0 0 0]
clip_matrix for max8=  [1 2 3 4 5 6 7 8 8 8]
clip_matrix is =  [2 2 3 4 5 6 7 8 8 8]


In [27]:
m1=np.array([1.2, 2.5, 3.8])
m2=np.ceil(m1)
print(m2)

[2. 3. 4.]


In [29]:
m=np.array([1,2,3,4,5,6,7,8,9])
m1=np.where(m > 5,100, m)
print(m1)

[  1   2   3   4   5 100 100 100 100]


In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

np.array([1, 2, 3]) is a 1D array
np.array([[1, 2, 3]]) is a 2D array